services:
  pocketbase:
    image: prateekrajgautam/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - 127.0.0.1:8090:8090
    volumes:
      - ${PB_DATA_DIR:-./pb_data}:/pb_data
    environment:
      - EMAIL=${EMAIL:-admin@example.com}
      - PASSWORD=${PASSWORD:-admin}
